Traceback (most recent call last):
  File "/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/manage.py", line 29, in <module>
    main()
  File "/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/manage.py", line 25, in main
    execute_from_command_line(sys.argv)
  File "/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/venv/lib/python3.12/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
    super().run_from_argv(argv)
  File "/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/venv/lib/python3.12/site-packages/django/core/management/commands/test.py", line 63, in handle
    failures = test_runner.run_tests(test_labels)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/venv/lib/python3.12/site-packages/django/test/runner.py", line 1059, in run_tests
    suite = self.build_suite(test_labels)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/venv/lib/python3.12/site-packages/django/test/runner.py", line 914, in build_suite
    tests = self.load_tests_for_label(label, discover_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/venv/lib/python3.12/site-packages/django/test/runner.py", line 895, in load_tests_for_label
    tests = self.test_loader.discover(start_dir=label, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/loader.py", line 309, in discover
    tests = list(self._find_tests(start_dir, pattern))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/loader.py", line 364, in _find_tests
    tests, should_recurse = self._find_test_path(full_path, pattern)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/loader.py", line 416, in _find_test_path
    raise ImportError(
ImportError: 'tests' module incorrectly imported from '/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/konveyor/apps/search/tests'. Expected '/Users/nikhild/Documents/job_related/projects/Exploratory/Azure AI Hackathon/Konveyor/konveyor/apps/search'. Is this module globally installed?
